### ISSUE TITLE
Agile grenoble - 404 not found

### ISSUE THREAD

**Issue by ptaillard** [cfpio/callForPapers#112]
Salut,
On vient de me remonter ce cas lorsque l'on essaie d'accéder à https://agile-grenoble.cfp.io/:
Redirigé sur https://agile-grenoble.cfp.io/null
Failed to load resource: the server responded with a status of 404 (Not Found)

J'ai reproduit le cas: Il faut que l'utilisateur soit connecté à son compte Google avant d'accéder à cette adresse et là j'obtiens tout le temps l'erreur.

Si je peux vous donner plus d'info, n'hésitez pas à me le demander
Pierre

**Comment by ndeloof** [comment]
j'ai essayé avec mon compte google et je ne reproduis pas l'erreur. Vu que tu y arrive, peux tu stp capturer un HAR en utilisant les developer tools de chrome et en cochant la case "preserve logs" dans l'onglet network ?

**Comment by ptaillard** [comment]
[agile-grenoble.cfp.io.zip](https://github.com/cfpio/callForPapers/files/305508/agile-grenoble.cfp.io.zip)
Voila le résultat..
Par contre,j 'ai eu plus de mal à la reproduire... Vous avez fait des corrections?

**Comment by jljouannic** [comment]
Reproduit à l'instant sur mon environnement de dev. J'enquête.

**Comment by jljouannic** [comment]
Fixed in https://github.com/cfpio/front-legacy/commit/13000ccb1c2b4a7840f6fa263ac96f7c59162775
