### ISSUE TITLE
Customisation du mail orateur pour Agile Grenoble

### ISSUE THREAD

**Issue by ptaillard** [cfpio/callForPapers#113]
On aimerait pouvoir customiser le mail envoyé à l'orateur suite à une soumission d'une session de sa part.
Actuellement, le mail reçu est celui-ci:
![capture](https://cloud.githubusercontent.com/assets/1677806/15892128/58f77322-2d78-11e6-8de9-2d741621268a.PNG)
On aimerait pouvoir le customiser pour Agile Grenoble.

**Comment by ndeloof** [comment]
la suppression du logo spécifique au breizhcamp est un minimum. On pourra par la suite le remplacer par la logo de l'événement (https://github.com/cfpio/callForPapers/issues/91)

**Comment by ptaillard** [comment]
Très bonne idée, pour Agile Grenoble ça suffira bien si l'on a juste la suppression du logo.
Par contre, pour le mail de contact, c'est le votre. Faudrait peut etre aussi le changer, qu'en penses tu? Car sinon vous risquez d'etre spammé par des demandes d'orateurs d'Agile Grenoble.

**Comment by ndeloof** [comment]
en effet.

**Comment by alexthomazo** [comment]
J'ai rajouté et pris en compte les champs en base (logoUrl et contactMail) mais pas encore de possibilité de le configurer dans l'IHM
