### ISSUE TITLE
Erreurs lors de la création de compte 

### ISSUE THREAD

**Issue by ptaillard** [cfpio/callForPapers#115]
En tant que participant, création de compte impossible (obligé de passer par sign-in google).
On a eu divers problème de connexion par des comptes autres que google.

**Comment by ndeloof** [comment]
svp donne plus de détails et/ou capture un HAR de la séquence de signup / login

**Comment by ptaillard** [comment]
Le cas ici est lors de la creation d'un nouveau compte. J'ai reçu un mail et et j'ai cliqué sur la validation le compte. J'ai rentré mon mot de passe et j'ai eu une erreur.
[auth.cfp.io.zip](https://github.com/cfpio/callForPapers/files/305495/auth.cfp.io.zip)

**Comment by ptaillard** [comment]
Quand je souhaite me connecter avec Github, et que je clique sur le lien GitHub, j'ai cette erreur:
Your email is not set, choose another provider
[auth.cfp.io.github.zip](https://github.com/cfpio/callForPapers/files/305499/auth.cfp.io.github.zip)

**Comment by ndeloof** [comment]
pour github c'est tout à fait possible, un compte github n'a pas forcément d'email renseigné, auquel cas le message te dis juste que ... ben ça le fait pas.

**Comment by ptaillard** [comment]
Suite à ton message, j'ai regardé mon compte Github. J'ai bien un email renseigné... sauf qu'il n'est pas public. C'est donc pour ça que ça ne fonctionne pas. Je l'ai modifié en 'public' et c'est nickel!
Merci pour ton aide

**Comment by ndeloof** [comment]
ce serait bien du coup qu'on améliore le message d'erreur avec peut être une page de guide pour expliquer ça.

**Comment by alexthomazo** [comment]
Redirection vers la home page si le cookie "returnTo" n'est pas défini : https://github.com/cfpio/auth/commit/7cfd73f6a512212a3625440d1c4f96d922aed199#diff-a0fcef6f8997e66226abe9e96b134f17R74

J'ai essayé de mettre un message un peu plus explicite pour le mail qu'on arrive pas à récupérer : https://github.com/cfpio/auth/commit/bb6cc31930a83aaf31d67797eda73c1fb4f7977b

**Comment by ptaillard** [comment]
Super, merci. Je viens de faire quelques tests et ça fonctionne parfaitement.

**Comment by ptaillard** [comment]
Je viens de m'apercevoir que dans la partie 'configuration' pour les admins, il y a un problème de templating.
Je met une issue spécifique pour ne pas polluer cette issue qui n'a rien à voir
