### ISSUE TITLE
Problème de redirection lors de la déconnexion

### ISSUE THREAD

**Issue by ptaillard** [cfpio/callForPapers#118]
Lorsque l'on est connecté et que l'on se déconnecte, on est redirigé vers http://auth.cfp.io/.
Si on se reconnecte à partir de cette page, on ne se retrouve plus sur agile-grenoble.cfp.io/dashboard Car il manque à l'url de http://auth.cfp.io  la target /?target=https%3A%2F%2Fagile-grenoble.cfp.io%2F%23%2Fdashboard

**Comment by alexthomazo** [comment]
Devrait être réglé avec https://github.com/cfpio/auth/commit/048024c209b960268d69718c45bdb2f1933f3a68
