### ISSUE TITLE
Administration : Les filtres par catégories ne fonctionnent pas

### ISSUE THREAD

**Issue by MichaelBitard** [cfpio/callForPapers#126]
Dans le tri du tableau des conférences, on à bien un select permettant de filtrer par catégorie, mais il ne fonctionne pas. Ça semble dû au fait que ce champ est toujours à " " dans les talks.

**Comment by alexthomazo** [comment]
Le filtre a été corrigé dans l'appli frontLegacy (les données dans la colonne s'affichent aussi)
