### ISSUE TITLE
i18n issue on SaaS version

### ISSUE THREAD

**Issue by ctranxuan** [cfpio/callForPapers#136]
Hello, 
In the contact version, there is a property that is not replaced: {admin.schedule}
See the screenshot...
![screenshot from 2016-11-15 08-50-15](https://cloud.githubusercontent.com/assets/816144/20297617/b1360e1a-ab11-11e6-80c6-7fe3e4a74d9a.png)

**Comment by alexthomazo** [comment]
fixed in front legacy (the tab has been removed)
