### ISSUE TITLE
[Admin] Failing link in contact notification mail from admin

### ISSUE THREAD

**Issue by clacote** [cfpio/callForPapers#146]
When a speaker submits a message to a proposal, the email sent as notification is OK.

When an admin respond to this message, an another mail is sent, with the whole team emails as recipients. In this email, the link leads to a page like `https://mix-it.cfp.io/#/sessions/795?tab=contact`, which displays "Erreur de serveur" when loading, displaying no data. There is indeed a JS error: Error 500 when requesting `https://api.cfp.io/v0/proposals/795`, with response `{"timestamp":1486022017860,"status":500,"error":"Internal Server Error","exception":"class java.lang.NullPointerException","message":"java.lang.NullPointerException"}`

**Comment by sebbrousse** [comment]
Le problème a été corrigé avec cfpio/callForPapers#185
