### ISSUE TITLE
🙀 I can't write emojis to describe my abstract

### ISSUE THREAD

**Issue by k33g** [cfpio/callForPapers#154]
Emojis aren't supported in the fields of the abstract card and are replaced by ?? in the text

**Comment by ndeloof** [comment]
how did you entered them ? UTF-16
Can you please create a proposal to demonstrate this issue and enter as description "proof for https://github.com/cfpio/callForPapers/issues/154" thanks

**Comment by jljouannic** [comment]
Duplicate #152
