### ISSUE TITLE
[Admin] Data writing conflict between Reviewers & Admins

### ISSUE THREAD

**Issue by youenchene** [cfpio/callForPapers#158]
Tested on https://codeursenseine.cfp.io .

When change and save the admin list it also replace completely the reviewer list.

![image](https://cloud.githubusercontent.com/assets/1607244/25098150/c51efb26-23a7-11e7-846c-68be41363e35.png)

![image](https://cloud.githubusercontent.com/assets/1607244/25098160/cd9660aa-23a7-11e7-99df-31335ae05c42.png)

**Comment by ndeloof** [comment]
@youenchene "reviewer" is not implemented yet, yo can just ignore this

**Comment by ndeloof** [comment]
you should first ask on slack :P

**Comment by youenchene** [comment]
XD

You need to feature flag the menu.

Can you invite me on the cfp.io slack please?
