### ISSUE TITLE
get hosted on Clever-Cloud

### ISSUE THREAD

**Issue by ndeloof** [cfpio/callForPapers#161]
We can host on Google Cloud, so "Clever Could" as well 

we can't use docker-compose anymore (?) how to get hosted with :

- [ ] static frontend(s) content - we'd like to split UI development in 3 distinct projects
- [ ] ngingx config and certificate

maybe we should have CI to assemble them altogether as a single app / docker image

- [ ] mysql DB migration

**Comment by waxzce** [comment]
like it's not write in the documentation (ahem) you can route on domain name AND path begin. SSL termination is manage by Clever Cloud

anyway, docker compose work on Clever Cloud

but the real luxury of Clever Cloud is to just code and push

**Comment by ndeloof** [comment]
so
- [ ] deploy API backend as a "jar" application -> `*.cfp.io/api`
- [ ] deploy frontend as a "static" application (or anything comparable) -> `*.cfp.io`
- [ ] set ssl certificate
- [ ] migrate database

I'll give it a try using our staging domain "cfp.one"

**Comment by ldoguin** [comment]
Hello, taking over for @waxzce here if you still want to do it. And also you do not need to set an ssl certificate anymore, we can automate it with Let's Encrypt. So do you still want to do it?

**Comment by ndeloof** [comment]
we still want, just miss time to migrate

**Comment by ldoguin** [comment]
Well please let me know if you need any help :)

**Comment by sebbrousse** [comment]
I think we can close this issue.
