### ISSUE TITLE
Error toaster when replying to a question in the contact tab

### ISSUE THREAD

**Issue by padewitte** [cfpio/callForPapers#171]
Today was asked a question in the DevFest Nantes CFP. I tried to answer more that 6 times and only see a toaster "Server error". After refreshing the page it appears that there were no error and see my 6 answers. As the toaster disappear quickly and as i can not remove an answer i was not able to take a screen shot.

**Comment by sebbrousse** [comment]
Le problème a été corrigé avec cfpio/callForPapers#185
