### ISSUE TITLE
Return to line in description should be espaced in CSV export

### ISSUE THREAD

**Issue by JulienDelRio** [cfpio/callForPapers#172]
In CSV export, the description data break the CSV format.

Return to line in description should be replaced by \n or URL escaped with %0A.

**Comment by alexthomazo** [comment]
Hi,
In the "standard" (RFC 4180), line returns has to be in plain text and escape with double quotes (https://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules).

If I open the file in LibreOffice, the parsing is OK.

Which parser do you use ?

**Comment by JulienDelRio** [comment]
I use Excel parser. Maybe I missed an option, i will check. Or I willuse Libre Office.
Thank you for the answer.

**Comment by alexthomazo** [comment]
Do not hesitate to reopen if you're blocked on reading ;)
