### ISSUE TITLE
Page d'accueil vide

### ISSUE THREAD

**Issue by hasalex** [cfpio/callForPapers#184]
Quand je me connecte à la page d'une conférence, et si je suis déjà authentifié, la page d'accueil est vide.

Il y a une erreur 404 pour la requête https://api.cfp.io/api/application, probablement due à la perte de la 1° lettre du nom de la conférence :
`{"timestamp":1517159670172,"status":404,"error":"Not Found","exception":"class io.cfp.domain.exception.NotFoundException","message":"No event with ID: reizhcamp"}`

**Comment by hasalex** [comment]
Pour me connecter, je dois ajouter un lettre au début de l'URL : http://xbreizhcamp.cfp.io/

**Comment by sebbrousse** [comment]
Il faut surtout se connecter en http**S**://breizhcamp.cfp.io (ou tout autre conférence). Dans le passage à Clever, on a perdu notre ancien reverser proxy qui s'occupait de ça, et on n'a pas encore pris le temps de l'embarquer dans l'application.

**Comment by hasalex** [comment]
OK, merci Sébastien.
Donc ça marche avec l'authentification parce que dans ce cas-là il y a redirection en https.
