### ISSUE TITLE
Let speaker re-use his bio

### ISSUE THREAD

**Issue by ndeloof** [cfpio/callForPapers#49]
As a speaker
when I have already applied to a CFP, and want to apply to another one
I want an option to just reuse my existing bio 
- [ ] split 'user' table into 'user' + 'profile'
- [ ] add a "language" attribute to profile. 
- [ ] API for lo list available profiles
- [ ] UI changes for user to select existing profile or create a fresh new one

**Comment by mimah** [comment]
Est ce que ce n'est pas que la bio du profil qui est dans ce cas ? Les autres infos restent inchangées quelle que soit la conf (nom, prénom, social, company, phone, gender...)

**Comment by ndeloof** [comment]
@mimah en effet. 
faudrait voir avec @sebbrousse ce qu'il avait en tête pour l'API speakers sur ce sujet
