### ISSUE TITLE
Let speaker re-use a proposal

### ISSUE THREAD

**Issue by ndeloof** [cfpio/callForPapers#50]
- [ ] Option for speaker to promote a proposal into his "portfolio"
- [ ] Option for speaker to select a proposal from portfolio when submitting a talk
- [ ] Automatically fill the `references` based on approval on other events.

**Comment by mimah** [comment]
Je prends le refactoring.

**Comment by ndeloof** [comment]
niveau UI, je suggère d'ajouter en dessous du `New proposal` un `Select from my Portfolio  ... `.
Niveau data ... pas sur
Ca serait sympa aussi si sur édition d'un talk de ce type on avait une option `Edit from portfolio | Create a copy`

**Comment by mimah** [comment]
En fait je suis parti sur une liste de talks que le speaker peut créer, modifier, supprimer.
Après il peut se balader dans cette liste et choisir de soumettre un talk ; les données du talk sont alors copiées dans une proposal (name, description, language, references, difficulty) et il lui reste à remplir les données propres à l'Event (format, track, co-speakers). Et je garde un lien entre la proposal et le talk pour faire du tracking pour les références par exemple.

**Comment by ndeloof** [comment]
ça le fait. Et ça n'empêche pas l'idée du "promote" sur une proposition en mode classique.
