### ISSUE TITLE
Sessions export does nothing when I click on "export"

### ISSUE THREAD

**Issue by jak78** [cfpio/callForPapers#77]
When I click on "Exporter, nothing happens. I was expecting some kind of download to CVS or Excel.
<img width="615" alt="capture d ecran 2016-05-17 a 22 47 51" src="https://cloud.githubusercontent.com/assets/351773/15338740/81f853c0-1c81-11e6-825b-267801e5a12d.png">

**Comment by mimah** [comment]
L'implémentation de l'export a été viré car elle était spécifique BreizhCamp, j'ai donc viré le bouton.
Mais on peut très bien imaginer un autre export, mais il faut le spécifier.

**Comment by jak78** [comment]
L'export serait très utile pour produire le programme publié sur internet
et imprimé en papier. Sinon, il y a une API ?

**Comment by mimah** [comment]
Pour l'instant non, mais fait une issue avec les spec que tu estimes être utiles pour un export

**Comment by jak78** [comment]
Voici ma proposition : https://github.com/cfpio/callForPapers/issues/83

**Comment by ndeloof** [comment]
@mimah on exportait pas au format sched.org ?

**Comment by mimah** [comment]
@ndeloof vu le code qu'il y avait derrière ce bouton je ne pense pas. Mais peut être qu'il est fait autre part.
