### ISSUE TITLE
code cleanup

### ISSUE THREAD

**Issue by nbulteau** [cfpio/callForPapers#8]

**Comment by nbulteau** [comment]
delete des classes : 
io.cfp.domain.admin.session.Track
io.cfp.domain.admin.session.Redirect
io.cfp.domain.admin.session.Uri
io.cfp.dto.mapping.CommentMapping
io.cfp.dto.mapping.RateMapping
io.cfp.dto.mapping.TalkMapping

**Comment by ndeloof** [comment]
closing. This is a continuous effort :)

**Comment by jljouannic** [comment]
Why have Orika mapping files been deleted (`TalkMapping`, `RateMapping`…)?

issue #118 may be a consequence of the deletion.
