### ISSUE TITLE
Bouton conférenciers

### ISSUE THREAD

**Issue by jak78** [cfpio/callForPapers#80]
<img width="397" alt="capture d ecran 2016-05-18 a 11 00 40" src="https://cloud.githubusercontent.com/assets/351773/15353220/326257c2-1ce8-11e6-986e-1493bdbe7a65.png">
Ce bouton affiche "7" mais je n'ai qu'un seul conférencier dans mon test.

**Comment by jak78** [comment]
Ce qui me serait utile en tant que sélectionneur c’est une sorte de « select count(soumissionnaire) ... group by soumissionnaire » sur les sessions validées par le soumissionnaire (pas forcément les drafts)

**Comment by ndeloof** [comment]
bug dans AdminStatsService#getAdminMeter qui compte tous les users de cfp.io (code legacy)
On ne peut plus faire un simple `count from Users`
Il faut faire un count des speakers et co-speakers.
