### ISSUE TITLE
Redirection loop when guest user tries to access an instance homepage

### ISSUE THREAD

**Issue by jeantil** [cfpio/callForPapers#94]
Nicolas created the scalaio.cfp.io instance for us to evaluate. 
When I followed the link from his email I got stuck in a redirect loop for about 40seconds before I got redirected to auth.cfp.io

I attached the har file with all the calls logged to this issue.
[auth.cfp.io.har.zip](https://github.com/cfpio/callForPapers/files/281423/auth.cfp.io.har.zip)

**Comment by ndeloof** [comment]
fixed
