### ISSUE TITLE
Integrate gravatar profile images

### ISSUE THREAD

**Issue by jeantil** [cfpio/callForPapers#95]
At the moment is seems it is mandatory to provide a link to a profile image to cfp.io, it would be nice to default to gravatar if an image isn't provided (avoids the need to update dozens of profile images :) )

**Comment by ndeloof** [comment]
could probably just make https://avatars.io/gravatar/{{user.email}} the default value until overriden

**Comment by ndeloof** [comment]
a very clever profile page would be able to detect no gravatar has been set for user email then fallback to twitter or github one :P
